### ISSUE TITLE
SD.h on Teensy3.5

### ISSUE THREAD

**Issue by charleslin525** [PaulStoffregen/SD#16]
Hi there,

I moved my project from Arduino Mega to Teensy 3.5. I tried to use the external microsd card adapter rather than the built-in sd card slot. The problem is I cannot access the card when using the standard cardinfo sketch. Are there any places in head files I need to change so that I can just use regular SPI connection to SD card adapter? I am sure the teensy 3.5 board and sd card have no issue, because I have tested on teensy 3.2 and Mega board, they all work well. It doesnt work on two of my Teensy 3.5.

**Comment by PaulStoffregen** [comment]
Use SD.begin(pin).  See any of the library's examples for details.

If it's still not working, post on the forum.  Show photos of the actual hardware connections in your forum post!
