### ISSUE TITLE
fatal error: FS.h: No such file or directory with Teensy 4.0

### ISSUE THREAD

**Issue by UV-Arpan** [PaulStoffregen/SD#26]
Getting error below with Teensy 4.0
fatal error: FS.h: No such file or directory

**Comment by PaulStoffregen** [comment]
You need the latest core lib: https://github.com/PaulStoffregen/cores

We're changing how filesystems work on Teensy.  You grabbed the github code early in this new way.  Details here.

https://forum.pjrc.com/threads/64136-File-abstraction-and-SdFat-integration
