### ISSUE TITLE
FS.h not found ;(

### ISSUE THREAD

**Issue by play113** [PaulStoffregen/SD#28]
In file included from include/main.h:5:0,
                 from src/main.cpp:1:
include/SD.h:35:16: fatal error: FS.h: No such file or directory

**Comment by PaulStoffregen** [comment]
You need the latest core lib which has [FS.h](https://github.com/PaulStoffregen/cores/blob/master/teensy4/FS.h)

Easiest way is to install this beta version, so you get everything updated.
https://forum.pjrc.com/threads/64592-Teensyduino-1-54-Beta-5

**Comment by play113** [comment]
THX for your very fast response ...
